[package]
name = "khanpython/dispense-prop"
description = "A promise-based system for physically dispensing and attracting in-game props."
version = "1.1.1"
license = "MIT"
authors = ["khanpython (https://github.com/KhanPython)"]
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
exclude = [".vscode"]

[dependencies]
promise = "evaera/promise@4.0.0"
janitor = "howmanysmall/janitor@1.15.6"