[package]
name = "khanpython/dispense-prop"
description = "A system for physically dispensing and attracting in-game props."
version = "3.0.0"
license = "MIT"
authors = ["khanpython (https://github.com/KhanPython)"]
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
exclude = [".vscode"]

[dependencies]
promise = "evaera/promise@4.0.0"
janitor = "howmanysmall/janitor@1.15.6"