[package]
name = "khanpython/dispense-prop"
description = "System for physically dispensing and attracting in-game props towards a target."
version = "4.2.0"
license = "MIT"
authors = ["khanpython (https://github.com/KhanPython)"]
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
exclude = [".vscode"]

[dependencies]
